name: Deploy Backend to DigitalOcean

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Repo
      uses: actions/checkout@v3

    - name: 🚀 Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USER }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          cd /root/assignments/PatientRecoverySystem/PatientRecoverySystem
          git reset --hard HEAD
          git pull origin main

          docker compose pull
          docker compose build api notificationservice
          docker compose up -d api notificationservice
